### ISSUE TITLE
Raw Notes from Meeting

### ISSUE THREAD

**Issue by anthonysuen** [data-8/literature-connector#3]
Shanaaz and Brian

Use Sci-kit Learn
- Students will use that
- The basis of all this.
- document term matrix
- Run cosign similarities for each roll.
- Normalize all the values.
- Cosign and the vectors
- Each text will be represented in point in space..
- How much the vectors are overlapping each other..
- Make a visualization and do the cosign frequency..
- Euclidian distance and coSin similiarity
- Correlation shows up

Middle 4-6 classes will work with notebooks.

Able to make a humanistic argument.

Want the students able to make humanistic argument based on data analysis.

Recreate a few different projects

Data phase, and how they use data to analyze them

Pithy of way of describe projects. Structure of Anglo Saxon society.
-      Stylistics. Give you information about alliteration.
-      Begin the day with a graph that she had used as the basis
-      spend the day recreating the graph..
- Machine

Tensor Flow

**Comment by teddyroland** [comment]
Not using RAs to develop course material.
